matrix:
  include:
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.1.9.3+
    - rvm: 2.3.0
      gemfile: gemfiles/Gemfile.1.9.3+
      env: COVERAGE=true
    - rvm: jruby
      gemfile: gemfiles/Gemfile.1.9.3+
# ppc64le related code
    - rvm: 2.0.0
      arch: ppc64le
      gemfile: gemfiles/Gemfile.1.9.3+
    - rvm: 2.3.0
      arch: ppc64le
      gemfile: gemfiles/Gemfile.1.9.3+
      env: COVERAGE=true
    - rvm: jruby
      arch: ppc64le
      gemfile: gemfiles/Gemfile.1.9.3+

before_install:
  - gem install bundler
